# Generated by Django 5.0 on 2024-01-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mike',
            field=models.DateField(blank=True, null=True),
        ),
    ]
